const express = require("express");
const multer = require("multer");
const { exec } = require("child_process");
const { writeFile } = require("fs/promises");

const upload = multer({ dest: "uploads/" });

const router = express.Router();

router.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "client", "index.html"));
});

router.post("/execute/node", upload.single("codeImage"), (req, res) => {
  const code = req.file;

  if (!code) {
    return res.status(400).send("Code image not provided");
  }

  const tesseractCmd = `tesseract ${req.file.path} stdout -l eng --oem 1 --psm 7`;

  exec(tesseractCmd, async (error, stdout, stderr) => {
    if (error) {
      console.error(`Error: ${error.message}`);
      return res.status(500).send(error.message);
    }

    const tempFile = "tempAutoGenerated.js";
    const nodeCmd = `node ${tempFile}`;
    await writeFile(tempFile, stdout);

    exec(nodeCmd, (error, stdout, stderr) => {
      if (error) {
        console.error(`Error: ${error.message}`);
        res.status(500).send(error.message);
      } else {
        res.status(200).json({ stdout });
      }
    });
  });
});

module.exports = router;
